#!groovy
// The above triggers groovy syntax highlighting in vim

buildscript {
    repositories {
        mavenCentral()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "com.gradle.publish:plugin-publish-plugin:${gradlePublishPluginVersion}"
    }
}

// Apply the Plugin Publish plugin to make plugin publication possible.  The Plugin Publish plugin
// will in turn auto-apply the Gradle Plugin Development Plugin (java-gradle-plugin) and the Maven
// Publish plugin (maven-publish).
plugins {
    id "com.vanniktech.maven.publish" version "0.32.0"
}
apply plugin: "com.gradle.plugin-publish"
apply plugin: "groovy"
apply plugin: "signing"
apply plugin: "idea"
sourceCompatibility = 1.8
targetCompatibility = 1.8

// Release version that won't conflict with the bintray plugin
//def releaseVersion = propertiesPluginVersion
group = "net.saliman"
archivesBaseName = "gradle-properties-plugin"
version = propertiesPluginVersion

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    implementation gradleApi()
    implementation localGroovy()
    testImplementation "junit:junit:${junitVersion}"
}

task sourceJar(type: Jar) {
    description = "An archive of the source code for Maven Central"
    archiveClassifier = "sources"
    from sourceSets.main.groovy
}

task groovydocJar(type: Jar, dependsOn: groovydoc) {
    description = "An archive of the GroovyDocs for Maven Central"
    archiveClassifier = "javadoc"
    from groovydoc
}

// Configure the Gradle Publishing plugin. Note that the ID must match it's Gradle Plugin Portal id
gradlePlugin {
    website = "https://github.com/stevesaliman/gradle-properties-plugin"
    vcsUrl = "https://github.com/stevesaliman/gradle-properties-plugin.git"
    plugins {
        propertiesPlugin {
            id = "net.saliman.properties"
            displayName = "Gradle Properties Plugin"
            description = "A Gradle plugin for loading and working with properties, enhancing Gradle's built in functionality."
            implementationClass = "net.saliman.gradle.plugin.properties.PropertiesPlugin"
            tags.set(["properties"])
        }
    }
}

// Configure the Vanniktech publishing plugin.
mavenPublishing {
    coordinates(group, archivesBaseName, propertiesPluginVersion)
    signAllPublications()
    // The vanniktech plugin is supposed to default to Maven Central, but as of 6/21/25, it still
    // defaults to the old OSSRH site.
    publishToMavenCentral(com.vanniktech.maven.publish.SonatypeHost.CENTRAL_PORTAL)
    pom {
        name = "Gradle Properties Plugin"
        description = "A Gradle plugin for loading and working with properties, enhancing Gradle's built in functionality."
        url = "https://github.com/stevesaliman/gradle-properties-plugin"
        licenses {
            license {
                name = "The Apache License, Version 2.0"
                url = "http://www.apache.org/licenses/LICENSE-2.0.txt"
                distribution = "http://www.apache.org/licenses/LICENSE-2.0.txt"
            }
        }
        developers {
            developer {
                id = "stevesaliman"
                name = "Steven C. Saliman"
                url = "https://github.com/stevesaliman/"
            }
        }
        scm {
            url = "https://github.com/stevesaliman/gradle-properties-plugin"
            connection = "scm:https://stevesaliman@github.com/stevesaliman/gradle-properties-plugin"
            developerConnection = "scm:git@github.com:stevesaliman/gradle-properties-plugin.git"
        }
    }
}
