# What version of the properties plugin are we building?
propertiesPluginVersion=1.6.0

# Do we want to do automatic releases of Maven artifacts when we publish?
mavenCentralAutomaticPublishing=true
# When we download a maven dependency, should we also get source files?
downloadSources=false

# When we download a maven dependency, should we also get javadocs?
downloadJavadoc=false

# Plugin versions
gradlePublishPluginVersion=1.1.0

# Dependency versions
junitVersion=4.12

